platform :ios, '7.0'

target 'KWSiOSSDKObjC_Example' do
  pod 'KWSiOSSDKObjC', :path => '../'
  pod 'Firebase', '3.7.1'
  pod 'FirebaseMessaging', '1.2.0'
  
  target 'KWSiOSSDKObjC_Tests' do
      inherit! :search_paths
  end
end
