source 'https://github.com/CocoaPods/Specs.git'
source 'git@github.com:SuperAwesomeLTD/sa-private-pods-specs-ios.git'

use_frameworks!
inhibit_all_warnings!

platform :ios, '10.0'

target 'KWSiOSSDKObjC_Example' do
  pod 'KWSiOSSDKObjC', :path => '../'
  pod 'Firebase', '3.7.1'
  pod 'FirebaseMessaging', '1.2.0'

  target 'KWSiOSSDKObjC_Tests' do
      inherit! :search_paths
      pod 'Nimble', '7.3.1'     
      pod 'Mockingjay'
  end
  
  post_install do |installer|
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['SWIFT_VERSION'] = '4.2'
          end
      end
  end
end
