version: 2

references:
  ios_config: &ios_config
    macos:
      xcode: "9.3.0"

  create_temp_dir_for_temp_files: &create_temp_dir_for_temp_files
    run:
      name: Create temp folder
      command: mkdir -p temp/test-results

  delete_temp_folders: &delete_temp_folders
    run:
      name: Remove temporary files
      command: rm -r temp && rm -r vendor && rm -r output

  bootstrap: &bootstrap
    run:
      name: Bootstap
      command: |
        git clone "${SA_CONTINUOUS_INTEGRATION_GIT_REPO_URL}" "${SA_PATH_TO_CONTINUOUS_INTEGRATION_REPO}"
        ~./${SA_PATH_TO_CONTINUOUS_INTEGRATION_REPO}/bootstrap/bootstrap-mobile-ios-sdk.sh
        
  push_changes: &push_changes
    run:
      name: Commit and push changes 
      command: ~./${SA_PATH_TO_CONTINUOUS_INTEGRATION_REPO}/mobile/git-push-changes.sh

jobs:

  setup_workspace:
    <<: *ios_config
    steps:
      - checkout
      - *bootstrap
      - *create_temp_dir_for_temp_files
      - persist_to_workspace:
          root: "."
          paths:
            - "*"

  ## Run unit tests
  test_unit:
    <<: *ios_config
    steps:
      - attach_workspace:
          at: .
      - *bootstrap
      - run:
          name: Run unit tests
          command: PATH_TO_SCAN_OUTPUT=$PWD/temp/test-results fastlane run_all_tests
      - store_test_results:
          path: temp/test-results

  semantic_release:
    <<: *ios_config
    steps:
      - attach_workspace:
          at: .
      - *bootstrap
      - run:
          name: Run semantic release
          command: NAME_OF_CIRCLECI_VARIABLE_OF_REPO_NAME=$CIRCLE_PROJECT_REPONAME ~./${SA_PATH_TO_CONTINUOUS_INTEGRATION_REPO}/semantic-release/semantic-release.sh
      
  ## Bump the SDK versions
  bump_versions:
    <<: *ios_config
    steps:
      - attach_workspace:
          at: .
      - *bootstrap
      - run:
          name: Bump SDK version
          command: fastlane bump_versions
      - persist_to_workspace:
          root: "."
          paths:
            - "*"
      - *delete_temp_folders
      - *push_changes

  ## Run sdk push
  sdk_push:
    <<: *ios_config
    steps:
      - attach_workspace:
          at: .
      - *bootstrap
      - run:
          name: Push the SDK to CocoaPods
          command: fastlane sdk_push isPrivateRepo:${SA_MOBILE_IS_PUSH_TO_PRIVATE_REPO}  

workflows:
  version: 2
  ios_sdk_workflow:
    jobs:
      - setup_workspace:
          context: MOBILE_IOS_SDKS
      - test_unit:
          requires:
            - setup_workspace
      - semantic_release:
          requires:
            - test_unit
          filters:
            branches:
              only: master
      - bump_versions:
          requires:
            - test_unit
      - sdk_push:
          requires:
            - bump_versions