version: 2

## Declare de references
references:
  ## Docker image configurations
  ios_config: &ios_config
    macos:
      xcode: "9.3.0"

  ## Dependencies
  fastlane_dependencies: &fastlane_dependencies
    run:
      name: Download fastlane
      command: gem install fastlane --user-install

jobs:
  build-and-test:
    <<: *ios_config
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: run_all_tests
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - *fastlane_dependencies
      - run: 
          name: Install Gems
          command: bundle install
      - run:
          name: Fetch CocoaPods Specs
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      - run:
          working_directory: /Users/distiller/project/Example
          name: Install CocoaPods
          command: pod install --verbose
      - run:
          name: Run all tests
          command: fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

  ## Run sdk push
  sdk_push:
    <<: *ios_config
    steps:
      - checkout
      - *fastlane_dependencies
      - run:
          name: Set configs for git
          command: git config --global user.email ${GIT_COMMITTER_EMAIL} | git config --global user.name ${GIT_COMMITTER_NAME}
      - run:
          name: Push the SDK to CocoaPods
          ## this sdk push will need to be automated for the SEMVER and also 'isPrivateRepo'
          command: fastlane sdk_push type:patch isPrivateRepo:false   

workflows:
  version: 2
  workflow1:
    jobs:
      - build-and-test
      - sdk_push:
          requires:
            - build-and-test
          filters:
            branches:
              only: master