//
//  KWSSubscribeToken.h
//  Pods
//
//  Created by Gabriel Coman on 28/06/2016.
//
//  @brief:
//  This class is used to send a Firebase token to the KWS backend
//  The token is unique, is generated by Google Firebase (remotely) and is used
//  to send Remote Notifications to this user
//

#import <Foundation/Foundation.h>
#import "KWSRequest.h"

// subscribe token protocol
@protocol KWSSubscribeTokenProtocol <NSObject>

- (void) tokenWasSubscribed;
- (void) tokenSubscribeError;

@end

// subscribe token class
@interface KWSSubscribeToken : KWSRequest
// delegate
@property (nonatomic, weak) id<KWSSubscribeTokenProtocol> delegate;
@end
